### ISSUE TITLE
Results bigger than 65536 characters get truncated

### ISSUE THREAD

**Issue by erikdubbelboer** [stiang/recli#10]
```
recli -s -h rethinkdb-eu-1 "r.db('test').table('test').get('aa00a256-524d-479c-ab16-f9e7fa62b63b')" | wc -c
65536
```

```
recli -s -h rethinkdb-eu-1 "r.db('creativechecker').table('checks').get('aa00a256-524d-479c-ab16-f9e7fa62b63b')" | python -m json.tool
Extra data: line 2 column 1 - line 7 column 64662 (char 44 - 65536)
```

Looking at the output, it gets terminated somewhere in the middle of a string.

**Comment by erikdubbelboer** [comment]
I found the issue, it's the [`process.exit()`](https://github.com/stiang/recli/blob/master/index.js#L88) right after the `console.log()`:

```js

// Just build some really big string:
var o = {};
for (var i = 0; i < 1000000; i++) {
  o['' + i] = i;
}
var s = JSON.stringify(o);

// Print the string to stdout.
console.log(s);

// Print the length of the string to stderr.
console.error('real: ' + s.length);

// Without setTimeout:
// $ node test.js | wc -c                                                                                                                                                                                                                     
// real: 15777781
// 65536
//
// With setTimeout:
// $ node test.js | wc -c
// real: 15777781
// 15777782

setTimeout(function() {
  process.exit();
}, 100);
```

65536 is the size of the pipe buffer in most linux systems. So `console.log` is able to write this many bytes to stdout before it blocks. Normally it would continue writing once the other process starts consuming it. But when `process.exit()` is called immediately it shuts down nodejs before it can continue to write.

**Comment by erikdubbelboer** [comment]
See: https://nodejs.org/api/console.html#console_asynchronous_vs_synchronous_consoles

**Comment by stiang** [comment]
Nice catch, thanks! Very busy atm, but I’ll try to get your PR merged during the weekend. Don’t be shy about nagging me if it doesn’t happen.
